# Il a été dit :

testimonials = [
  {'msg': "Authmane a aider mon fils énormément. Ses notes en MEP 11ieme sont monte de 3 à 5 en 2 mois. En plus, maintenant il a du plaisir à apprendre. Authmane enseigne avec les utils informatique très à jour, qui sont très efficace pour les cours à distance. Ses seances d’entraînement sont un très bon idée pour renforcer le matière. Un prof 5 étoile",
  'avatar': 'female-pale.png',
  'name': "Mère d'Alexandre",
  'info': "11ème VP, Nyon",
  'source': 'spm'},
  {'msg': "Authmane est un super prof ! Il est patient, ses explications sont claires et sa méthode de travail efficace. Il est investi dans ses cours et mes progrès et sa plateforme est adaptée aux cours en ligne.",
  'avatar': 'female-black.png',
  'name': "Ingrid",
  'info': "Maturité suisse en autoditacte",
  'source': 'spm'},
  {'msg': "Authmane est incroyable! Extrêmement poli, correct et compétent (champion de maths, mais ses connaissances dans plusieurs domaines sont impressionnantes), mon fils (11eme) dit que personne explique les choses aussi bien que Authmane. Enfin, plus de stress avant les examens de maths et de maths-physics! À recommander sans aucune hésitation!",
  'avatar': 'female-pale.png',
  'name': "Mère de Soren",
  'info': "11ème VP, Nyon",
  'source': 'spm'},
  {'msg': "Nous sommes très contents des cours. Notre fils apprécie énormément la façon d'enseigner et l'efficacité. Il adore les maths à présent et attend avec impatience le prochain cours. Bravo et grand merci pour votre professionnalisme et gentillesse !",
  'avatar': 'female-glasses.png',
  'name': "Mère de Max",
  'info': "Apprenti informaticien",
  'source': 'spm'},
  {'msg': "Claire et précis, le meilleur pour t'assurer une bonne note lors de ton exam.",
  'avatar': 'male.png',
  'name': "Max",
  'info': "Apprenti informaticien",
  'source': 'spm'},
  {'msg': "Excellent ! Authmane est très patient et sait bien s'adapter au niveau de l'élève pour une meilleure compréhension.",
  'avatar': 'female-pale.png',
  'name': "Caroline",
  'info': "Infirmière",
  'source': 'spp'},
  {'msg': "Bonjour je m'appelle Rafael, j'ai 15 ans. J'ai passé mon examen de 11ème vp, au collège du Belvédère avec l'option spécifique Maths et Physique, avec succès et ça, en partie grâce a Authmane, qui m'a guidé pour apprendre des méthodes de travail ainsi que consolider mon bagage en Maths et Physique.",
  'avatar': 'male.png',
  'name': "Rafael",
  'info': "Lausanne, Collège du Belvédère",
  'source': 'gg'},
  {'msg': "M. Terki explique tout avec clarté et a fait en sorte que je ne doutais pas de ce que je faisais. Il a même pris plus de temps si nécessaire pour être sûr que j’avais tout compris correctement. Il est très patient et sait de quoi il parle, ce qui m’a aidé pour mes examens.",
  'avatar': 'male.png',
  'name': "Frederico Blanco",
  'info': "Lausanne, Gymnase de la Cité",
  'source': 'gg'},
  {'msg': "Parfait ! Jolan était content, il a compris beaucoup de choses et ça l’a bien aidé",
  'avatar': 'jolan.jpg',
  'name': "Mère de Jolan Gay",
  'info': "Horticulteur CFC",
  'source': 'spp'},
  {'msg': "Authmane is a good instructor who is patient and dedicated. He is helping me learn Algebra and other Maths subjects. Overall, I am satisfied his help and I would recommend him to anyone.",
  'avatar': 'male-black.png',
  'name': "Samson",
  'info': "Développeur web",
  'source': 'spm'},
  {'msg': "J’ai pris des cours de maths et de physique l’année passée avec lui et j’ai bien réussi à comprendre ce qu’il m’expliquer. Je me suis bcp amélioré grâce à ses cours.",
  'avatar': 'female-black.png',
  'name': "Alisson Lopez",
  'info': "Gymnase de Provence",
  'source': 'spm'},
  {'msg': "Le prof est super rien à dire ! Pour moi il a une façon d’expliquer que j’aurais beaucoup voulu avoir durant ma scolarité. Personnellement il m’as sauvé pour la physique (ce que était le plus important pour mon année). Je le recommande vivement pour toute personne qui aurait différentes difficultés en maths ou autre.",
  'avatar': 'male.png',
  'name': "Dimitri",
  'info': "Vevey",
  'source': 'gg'},
  {'msg': "Je suis en deuxième année de gymnase et pour des raisons familiales j'ai du aller vivre à l'étranger pendant quelque mois. De se fait j'ai raté presque 4 mois de cours et n'avait pas les moyen de rattraper seul se que j'avais manqué. J'ai pris une trentaine d'heure de cours avec Authmane pour rattraper les mathématiques, la physique et la chimie. Les cours m'ont beaucoup plu et m'ont été très utiles. J'ai pu grâce à lui rattraper mon retard en peux de temps et pour un prix raisonnable.",
  'avatar': 'male.png',
  'name': "Alexandre Kleinheny",
  'info': "La Tour-de-Peilz",
  'source': 'gg'},
  {'msg': "Bonjour! J'ai eu une très bonne expérience avec Authmane Terki. Il sait prendre le temps avec chaque élève pour nous expliquer de manière à ce qu'on comprenne tous à notre manière. Il m'a beaucoup aidé à préparer mes examens de certificats. J'ai vu une grosse différence entre le avant et le après les cours avec lui. Je le conseille à toute personne ayant des difficultés en maths ou autre.",
  'avatar': 'female.png',
  'name': "Victoria Riesen",
  'info': "Renens, Collège du Léman",
  'source': 'gg'},
  {'msg': "Toute est super bien expliqué, étape par étape, Je recommande absolument!",
  'avatar': 'male.png',
  'name': "Damir",
  'info': "Vevey",
  'source': 'gg'},
  {'msg': "C'etait parfait! Merci",
  'avatar': 'male.png',
  'name': "Claudio",
  'info': "Participant à l'examen ECUS",
  'source': 'spm'},
  {'msg': "Super prof. Pour la première séance, ma fille a bien aimé sa façon de travailler. Méthodique, avec une grande capacité à transmettre l’information et bien expliquer les exercices difficiles .",
  'avatar': 'female.png',
  'name': "Mère de Alaa",
  'info': "9ème Harmos",
  'source': 'spm'},
  {'msg': "Sujets maîtrisés et explications claires, très sympathique. révisions efficaces pour la préparation aux examens",
  'avatar': 'male-beard.png',
  'name': "Père de Amira",
  'info': "11ème VP",
  'source': 'spp'},
  {'msg': "Authmane est très organisé, gentil et surtout investi dans le succès de ses élèves ! Mes notes se sont beaucoup améliorées grâce à lui.",
  'avatar': 'female-pale.png',
  'name': "Ally",
  'info': "Gymnase de Nyon",
  'source': 'spm'},
  {'msg': "Des explications claires et précises, un support de travail efficace et de la bonne humeur ! Le bon moyen de réviser ses maths !",
  'avatar': 'male.png',
  'name': "Dimitri",
  'info': "Gymnase Auguste Piccard",
  'source': 'spm'},
  {'msg': "Bonjour, Je vous recommande d’avoir les cours de maths avec Authmane car ces explications sont très claires et si on ne comprends pas, il nous dessine un schéma pour plus comprendre sa logique qui nous permet de mieux comprendre. Grâce à lui, je commence à m’améliorer en maths et commence à comprendre plus les logiques, problèmes, etc.",
  'avatar': 'female-black.png',
  'name': "Meghna",
  'info': "Maturité professionnelle, Genève",
  'source': 'spm'},
  {'msg': "Ma fille avait besoin d’appuis avant les examens de 11eme. Authmane est super, il a une méthode carrée et ses explications sont très claires! On apprécie également la rapidité de réponse!",
  'avatar': 'female.png',
  'name': "Mère de Camille",
  'info': "11ème VP",
  'source': 'spp'},
  {'msg': "Excellent prof, il m’a beaucoup aidé à combler mes lacunes et sa façon de faire est vraiment adaptée en fonction du thème traité.",
  'avatar': 'female-pale.png',
  'name': "Camille",
  'info': "11ème VP",
  'source': 'spm'}
] 

# {'msg': "",
# 'avatar': '',
# 'name': "",
# 'info': "",
# 'source': ''}
